### PR TITLE
Added PostgreSQL, Tomcat, MariaDB to server_item, dmidecode hardening

### PR DESCRIPTION
**Pull request by FranzXaver**
Added PostgreSQL to server / database info, tested only on Ubuntu so far

### CODE REVIEW

**Comment by mark-unwin** [comment]
Hi Xavier,
I love this work. My only concern is what happens on the 'sudo' line if we're running as a non-root user who doesn't have sudo allowed? Can you test this (I would, but I don't have a machine with PG installed right now). If the script stops and asks for a password, this won't work...
Thanks in advance.

**Comment by FranzXaver** [comment]
Good point, I will test this and come back to you.

**Comment by FranzXaver** [comment]
I added some more fixes:

- added MariaDB and PostgreSQL as separate Database
- added postgres server_item
- added tomcat instances server_item
- fix for mysql > 8, versioning was changed
- fix for invalid dmidecode settings where more than one line is returned

**Comment by FranzXaver** [comment]
Now also tested on Ubuntu and CentOS with MariaDB, mySQL and PostgreSQL

**Comment by FranzXaver** [comment]
@mark-unwin I can happily make a smaller pull request if you feel this is too much at once.

**Comment by mark-unwin** [comment]
Looks good - merged.
Thanks very much @FranzXaver !

**Pull request merged**
